name: skola_offline
description: A Flutter app for the skolaonline school system.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.13+16

environment:
  sdk: ^3.1.1

dependencies:
  # pluto_grid: ^8.0.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  html: ^0.15.4
  # flutter_html: ^2.1.2
  flutter_html: 3.0.0-beta.2
  flutter_html_all: 3.0.0-beta.2
  # flutter_widget_from_html: ^0.15.1
  intl: any
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  test: ^1.21.0
    
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter

  dynamic_color: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/
